sonar.projectKey=testtest00
sonar.projectName=test00
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://sonarqube.sat.almaviva.it:9000
sonar.login=sqp_651f085e97a810c8014dd6a7e67651011ba450f5
sonar.qualitygate.wait=true
sonar.http.proxyHost=5.175.50.110
sonar.http.proxyPort=4569
sonar.http.proxyUser=Mtest
sonar.http.proxyPassword=Marcello666
sonar.https.proxyHost=5.175.50.110
sonar.https.proxyPort=4569
sonar.https.proxyUser=Mtest
sonar.https.proxyPassword=Marcello666
