sonar.projectKey=sqp_02e0869598380f2d646107f43250eebad2c93e41
sonar.qualitygate.wait=true
sonar.host.url=http://sonarqube.sat.almaviva.it:9000
http.proxyHost=5.175.50.110
http.proxyPort=4569
http.proxyUser=Mtest
http.proxyPassword="I9W5P[{e6ckW?wC4(q;l"
https.proxyHost=5.175.50.110
https.proxyPort=4569
https.proxyUser=Mtest
https.proxyPassword="I9W5P[{e6ckW?wC4(q;l"
sonar.javaAdditionalOpts="-Dhttp.proxyHost=5.175.50.110 -Dhttp.proxyPort=4569 -Dhttps.proxyHost=5.175.50.110 -Dhttps.proxyPort=4569"
